on: [push]
    jobs:
    mail-on-push:
        runs-on: ubuntu-latest
        steps:
        - name: Send mail
            uses: dawidd6/action-send-mail@v3
            with:
            server_address: smtp.gmail.com
            server_port: 465
            username: ${{ secrets.MAIL_USERNAME }}
            password: ${{ secrets.MAIL_PASSWORD }}
            subject: Send mail
            to: kermoanijarv@gmail.com
            from: "Github Actions"
            body: "New Commit to Repo ${{ github.repository }} From ${{ github.event.pusher.name }}"
